---
packages:
# The essentials
  - libguestfs-tools
  - jq
  - yq
  - sudo
  - libgl1 
  - libegl1
  - inxi
  - ncdu
  - curl
  - rsync
# For container VMs
  - docker
  - podman
  - podman-compose
# For security
  - fail2ban
  - clamav
