postinst:
  hosts: 
    postinst1:
      ansible_host: 192.168.1.232

workers:
  hosts:
    192.168.1.2[32:35]:
    
webui:
  hosts:
    dev:
      ansible_host: 192.168.1.234

local:
  hosts:
    localhost:

labo:
  children:
    webui:
    workers:
    
vm:
  children:
    local:
