---
- name: Install a list of packages
  ansible.builtin.apt:
    pkg: "{{ packages }}"
  tags:
    - essentials
    - security_ssh_hardening

- name: Ensure .bashrc contains extra config
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: "{{ lookup('ansible.builtin.file', 'bashrc_extra') }}"
    state: present
  tags:
    - always

- name: Strengthening the SSH security of the server
  ansible.builtin.include_tasks:
    file: security_ssh_hardening.yml
    apply:
      tags:
        - security_ssh_hardening
  tags:
    - always
