---
- name: Make sure we have a 'wheel' group
  ansible.builtin.group:
    name: wheel
    state: present

# Allow 'wheel' group to have passwordless sudo
- name: Allow 'wheel' group to have passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers.d/wheel
    create: true
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

# Add sudoers users to wheel group
- name: Add sudoers users to wheel group
  ansible.builtin.user:
    name: "{{ ssh_user }}"
    groups: "wheel"
    append: true
    state: present
    createhome: true

# Add identity key to authorized keys on host
- name: Add identity key to authorized keys on host
  ansible.posix.authorized_key:
    user: "{{ ssh_user }}"
    key: "{{ lookup('file', ssh_identity_key) }}"
  register: add_identity_key
  when: ssh_identity_key is defined and ssh_user is defined

- name: Create jail.local for fail2ban
  ansible.builtin.shell: |-
    cat > /etc/fail2ban/jail.local <<EOF
    [sshd]
    enabled = true
    port = ssh
    filter = sshd
    logpath = /var/log/auth.log
    maxretry = 2
    findtime = 300
    bantime = 3600
    ignoreip = 127.0.0.1
    EOF
  notify: Restart fail2ban

# Enable SSH pubkey login
- name: Enable SSH pubkey login
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^(#\s*)?PubkeyAuthentication'
    line: "PubkeyAuthentication yes"
  notify: Restart sshd

# Disable empty password login
- name: Disable empty password login
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^(#\s*)?PermitEmptyPasswords'
    line: "PermitEmptyPasswords no"
  notify: Restart sshd

# Disable SSH root login
- name: Disable SSH root login
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^(#\s*)?PermitRootLogin'
    line: "PermitRootLogin no"
  notify: Restart sshd

# Disable password login
- name: Disable password login
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^(#\s*)?PasswordAuthentication'
    line: "PasswordAuthentication no"
  when:
    - add_identity_key is succeeded
    - not add_identity_key is skipped
  notify: Restart sshd

# Max authorized attempts to login
- name: Max authorized attempts to login
  ansible.builtin.lineinfile:
    dest: "{{ sshd_config }}"
    regexp: '^(#\s*)?MaxAuthTries'
    line: "MaxAuthTries 3"
  notify: Restart sshd