---
# handlers file for roles/bootstrap-vm
- name: Restart sshd
  ansible.builtin.service:
    name: "{{ sshd }}"
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: "fail2ban"
    state: restarted