postinst:
  hosts: 
    postinst1:
        ansible_host: 194.163.130.41

workers:
  hosts:
    194.163.130.4[0:3]:
    
webui:
  hosts:
    prod:
      ansible_host: 194.163.130.41

local:
  hosts:
    localhost:

labo:
  children:
    webui:
    workers:
    
vm:
  children:
    local:
