---

## Create .bashrc
- name: Ensure {{ ansible_env.HOME }}/.bashrc exists
  file: 
    path: "{{ ansible_env.HOME }}/.bashrc"
    state: touch
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0644'

- name: Ensure .bashrc contains extra config
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    block: "{{ lookup('ansible.builtin.file', 'bashrc_extra') }}"
    state: present
  tags:
    - always

## Execute compose for all apps given
- name: Execute compose
  ansible.builtin.include_tasks: tasks_setup_apps.yml
  loop: "{{ apps }}"
  tags:
    - setup_apps
    - restore_apps
    - restore

## Execute compose db backups for all apps given
- name: Execute compose db backups
  ansible.builtin.include_tasks: backup_databases.yml
  with_nested: 
  - "{{ apps }}"
  - "{{ databases }}"
  tags:
    - never
    - backup_db
    - backup

## Execute compose app backups for all apps given
- name: Execute compose apps backups
  ansible.builtin.include_tasks: backup_apps.yml
  loop: "{{ apps }}"
  tags:
    - never
    - backup_apps
    - backup

## Execute compose db restorations for all apps given
- name: Execute compose db restorations
  ansible.builtin.include_tasks: restore_databases.yml
  with_nested: 
  - "{{ apps }}"
  - "{{ databases }}"
  tags:
    - never
    - restore_db
    - restore